language: node_js
cache:
  directories:
    - node_modules
node_js:
  - lts/*
script:
  - npm run test:prod
after_success:
  - npm run report-coverage
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: GLct/WG8weyGwbVXr2a/uT/lKwvIr7kutWR20P1Z2Au6TWnwhre//JOBAmulne59IK1hrlazBqEZv7uS93ED5Qd11JZ+iMtWTXFMVIfUVXgz683UuaoNrDW0Cof/5qaDmADPnLp5HflB2Z2Juehc8ODZnVlJDMGZcdCYyTeb4Qi2VG/ejUBeU8nlgAonEFfIBqNxGY42qwfjLPcmmQhqf4rteJVv1AjZ5O94o7Go9jYUriW+LHIZbRbyziIg4i6/18O0H/XXGdNzHOvzozw0BTfi4QQ9emf83FLgAySmjlo1wodTt82s3RP39n11lBE1W9afRnrpJONzh9ULbqsWgAu+3+2AT7n8YaoLNTvf0vARaVu/xhKU7cqEw72S8cc6722LaG/soO9SienSQpE73NBN4kgp/SA9czB4QgLorRHLuiB0q1+OnvWKEAYEGg1yU00/qrGYsPuM/BPUw+k+cms4DTE4+T5f/Ruj2w2hpluhtpoULNhSYrfD4P40Xtogb9Vvp9tDfxVMTohXq/2diIiLKJuGl8Rj9Z5JaqZYrNKjpzTJdsC5z3EZp3IyjXimfnAy/SufisIStZIemaO50SmqLEgEO4/bFYY3Izh9YkeM2uf3segZoKQXs8SoQsHLt5yUefNf5aLZ2+B01b49eYPcnmQZsUwBY73+68YehtY=
    on:
      branch: master
      tags: true
