language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/*
script:
  - npm run test:prod
after_success:
  - npm run report-coverage
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: mSdgwJnZnHj18IQlSbg69hjBpMhmIban3GCHNsNTRvxlyo6X5Ka55FUTwpnyYlB5jnIr51zLAa7otWonpQQMVCo5KoOE3i98mwaitIFVV1mAQ10haf9tXS+u15tLOFh6/y8+TzK1/6+BX/jX2TkhkGJHuvUAnsYq67mVhef0Bg3gKeIiajts7n/9p9NPq7EHq/mssd1dtjdQKsw6IHawiXzwaVm102aZ1sLb6QvdFmwhkH+/rimhTyFbYeQk5QDW4AEDxxHelP7OpbWSnX6u8rshUIAMhL9gp6budHWW2v2b7/LJkJ0ZfkzF+xL1vXRQbjZMvxPM8PLnv422MwPhLrxXksouQy5Sd+jxzmayjq973zcbNKClv8F4j0SbcJfeEcGPTMQE12zH8123XdowK+3/Ea3BuRxple9oOIQ3V8czIBmUfSerp6A9sYunR+KvUsuXVbTaWLb0lfv2ooaecMLL9YjeDwlSngTPql1o79plEH5scl9P4qsyz2eieZKLrozOwkLFm9mAjM3gRi6FpmVAkbjOZHuHh74mG32O8cXbTgskHIFGOYw6OSnEeclyBi0yACPLr5zhvG2PbVR1GTdMKdJSh1oNNSXJLaARG8JGbgZVoEkNnx8oQT0GLCY5SiNPQ6KVJsUWMkh6yGZG1KNfNqIr9Toak8lUC1z7ve8=
    on:
      branch: master
      tags: true
