language: node_js
cache:
  directories:
    - node_modules
node_js:
  - lts/*
script:
  - npm run test:prod
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: nwe58/vlA4NgehJmyLCdU6GggwIWthpl79SYqelAhbcds7N39+lAP2GkRlwGdH3iO4OLV3v7kibnM9uniFzUDKSBl2GWjRoPf5dN9ElAr5YtzPXYkjm4uKgAt84b0bEStUyw+7IBBHvl6abmH4aVZyFkCFppvxd+oORb7efKy6AYXsGYQcQtkB84hczuOBLXj9m6jZJZOamIju8j/Bb3mEdls0SeVtjnzZ0AopLOhSnAvik4i/WEZ9fFqkpykaAzvypT3vht7EGjhE1jzz0d0cM2aMMcjHqpIe+1YUCXqa7sTNE9k22zWlhWtxNUzw1b8Bmt/xERk8oS/XcbkI8GORSt06h1KofEDIvq+FFP3P0ZMPEZavgGF38hu3QgVvnl693/wcyhP8ok5/5jJqorWPU71AjpywUEt/VYrYkoq6fo3mnsunWJJGkwKh3WWfgSpXHoYJxerhlIDxe40WpVpiKdWQqyaE7neLcsyFmgsxfW2yZvKEpIgyfAVtpeHYJ6AS8pUw9PXF+24OJ2ClCPYtQ8IU45uIdPZqms3K+FLFnTqCE1GBr/t7Tae8PAu3h2YpKQS4l7g2wZyBMxgI39hyU6kFGJTK7JbsvH11hfddi0JKyXwgYLVIPdCVjf5Z/QwlBt6rfITtsGcBlBsxjYzXy6dyJUGl3jV6vcSJxOsUU=
    on:
      branch: master
      tags: true
