language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - lts/*
script:
  - npm run test:prod
after_success:
  - npm run report-coverage
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: e3UvFZ1+q3fn0BxW99Kt9ivi1qYRRKVl6Om8nd/+PaKOC+zlUedBCUhbgsDYKDqR3x7dg2XPq7l9CN0xalBoJgndn7n1T9NqgDC26UAbl35wljRcAl7UxEQ6XxGjpqAAoxA0f/lX3MHUbV6/wNQgMQShHntmA4YiJe7lq6bCVX2C59mCqHm3eGfRDSw9X18fHR6IyEOIqp4PypjdJGmQzpM7uYTpf4Cnj8zPXL3ReGJikvGn1rugQalYIsbB0PhUJJiilZcPn5ci/TuM/HSYvU/aP3D91av+4iM8dlkNuvQ8GWZ+2J6AFRp0kIx/zbjQAHbHFrRNLjj3EwI5ODH1ganOHiUjvSMEsgOjrNeICjqu6kCkC3EZr8ytv88VqM5ViS3yh2tUD9pa7EOj2iW4WMz85qucXPw0Jh7Qkz/LlrD5UPFYtxHC21jlYkO/pQ6soV3Me6uWCGH6yHP1YkpSzMh3t/3XULpxR4+ru0275/Nrn87L606GdnGYzTGwyX63Y74fnzlPlyli6HrklYX+ZwLIOdeqcuZLeodypq/GWfbfjqcC7Y8cMIlHlvndYYtF+zUWrVnEDpbOb07xPqgauH045AryfXpo+49iPGV89BL9FaCb8H4RafomFl8K0fbuR4qSK+Y7IxeG34brBZtkaoRyoSnWdvLTBw2dg6WuDAE=
    on:
      branch: master
      tags: true
