language: node_js
cache:
  directories:
    - node_modules
node_js:
  - lts/*
script:
  - npm run test:prod
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: o2MdQQc8tu1lgMUQIY8IfAPbs8OsB8Zzz2yJRCHTA6bQLeKQ8M8lG/iZsHSSHqb+9dNMK0xj1e5/XqobOi5Jcv/AC/WOomfazhtJfx+/yyTsRLzVDtt8eb9BqLoKHE1T/Klsih2TyYtnZPQbIAImV4DTRECgDn08GSHxC1HylaMfCdFZgjmwI+xMKObcOnwWBf6nGI/np03ZVrNwtoegud4Zr6W5uIOMIUOWdg868H9/zQMcbatq8jukdsEu32sBCSHniT8rivnxTofyBlp4wvq+CPUa9NPLy4FTnFuuFmGFJ+9sWz5SN1pWXXTU7KK97Iej3eBOoT3AWmMUQ205GwNo8vB2/C5DEd44zxvNCd4bn6UccVKvev42v0V48uputJTMrKahO9vUtYxZNoScG/2dlE3j3esrHqafz+fns9b7NY1TvUgg9XTKHyzNHvqmWIXAf1ruUM4ZfqjVDhdkeacznU+/c8pkgMvLwMTadOA08iJyf+a/R8M5fiQ3v0DDl9HUxHVo5NEnm9V1JAtto/STq2+e++Qf696JvJGjlIhzrWR7yVZ+nhaNq4+OWwvjA9wEx1sMK+7qldwu8sugpK1Mgw/NTCPIDm81Ei6+lhh3rViPT54xfhrgs75byP7MErMpen2BEtrjIaiuIMlyb2hAHgP/1Ta9Ug2HYbef6y8=
    on:
      branch: master
      tags: true
