language: node_js
cache:
  directories:
    - node_modules
node_js:
  - lts/*
script:
  - npm run test:prod
deploy:
  - provider: npm
    email: phil@marketprotocol.io
    skip_cleanup: true
    api_key:
      secure: IzSMAvKHkQlA1ScBqGV2G2tagkf+PGelItFKByp1vekFoAACEaHGf6ursbkUlqSsokBE8EJ0VuBUsZeI1DMsKruwCQOciXSASlTocB68Q38Xjbt4zupkdJoX4xpTcMEMESRVbQRdNWnFwil5IpfK3t/3errqdNHe/o5ANWE2rwDZMBNDb6GNVvspAP+scqJZt3BOjm+jb7IWhsMRbkEpmni+A0tjiD9uFraJVY8g3VzLqX/dgrdfzc/0z4zrZ4bqHDse7HnzmxYOAI6Wgztk38To09HME5n+Q1BJfoOZd/OzRWhY7kgKcumLdURhOoKRtH9CwiiUA1OdzF8tQCPuirtgLfGhu07EZ/ndZPMcpgeYlx/vVbdMtU9q+n3sNe7hLTUDokJr1HGwUDNtS08jtU8DtAWgGXZe2vJ41BPyuDREWHTtPu2Sknr8eiTweUl3nCxwDLuiJnVT2hAstgZ0/EHhukvWA8vs7vY2QZIj5Xe72wbyKk//7yyssqnjSBUjMKlLe454+uZu67QMVU8WoMu2nGrZ7rGEZTQYuA1vGSlbbQ9PRpvDDGnNgcUilVZE7vKQZuCkhjXoM6+OtCXQc2zj5XSTTiSKhvG4zmfk7zSOb5t+5xwtyy2GGx3BSmKqMKkhnvXyhjuy5S10RToRz1h1Znrq5BhFHh2smUSvfIs=
    on:
      branch: master
      tags: true
