/* GENERATED BY TYPECHAIN VER. 0.2.4 */
/* tslint:disable */

import { BigNumber } from 'bignumber.js';
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper,
  DeferredEventWrapper
} from './typechain-runtime';

export class MarketToken extends TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: true,
        inputs: [],
        name: 'name',
        outputs: [{ name: '', type: 'string' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: '_spender', type: 'address' }, { name: '_value', type: 'uint256' }],
        name: 'approve',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'totalSupply',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: '_from', type: 'address' },
          { name: '_to', type: 'address' },
          { name: '_value', type: 'uint256' }
        ],
        name: 'transferFrom',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'INITIAL_SUPPLY',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'decimals',
        outputs: [{ name: '', type: 'uint8' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'upgradeableTarget',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: '_value', type: 'uint256' }],
        name: 'burn',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'value', type: 'uint256' }],
        name: 'upgrade',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: '_spender', type: 'address' },
          { name: '_subtractedValue', type: 'uint256' }
        ],
        name: 'decreaseApproval',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'minBalanceToAllowContractCreation',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: '_owner', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'lockQtyToAllowTrading',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'upgradeAddress', type: 'address' }],
        name: 'setUpgradeableTarget',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'owner',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'symbol',
        outputs: [{ name: '', type: 'string' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: '_to', type: 'address' }, { name: '_value', type: 'uint256' }],
        name: 'transfer',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'totalUpgraded',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: '_spender', type: 'address' }, { name: '_addedValue', type: 'uint256' }],
        name: 'increaseApproval',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: '_owner', type: 'address' }, { name: '_spender', type: 'address' }],
        name: 'allowance',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        inputs: [
          { name: 'qtyToLockForTrading', type: 'uint256' },
          { name: 'minBalanceForCreation', type: 'uint256' }
        ],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'constructor'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'contractAddress', type: 'address' },
          { indexed: true, name: 'userAddress', type: 'address' },
          { indexed: false, name: 'balance', type: 'uint256' }
        ],
        name: 'UpdatedUserLockedBalance',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'from', type: 'address' },
          { indexed: true, name: 'to', type: 'address' },
          { indexed: false, name: 'value', type: 'uint256' }
        ],
        name: 'Upgraded',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'burner', type: 'address' },
          { indexed: false, name: 'value', type: 'uint256' }
        ],
        name: 'Burn',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'owner', type: 'address' },
          { indexed: true, name: 'spender', type: 'address' },
          { indexed: false, name: 'value', type: 'uint256' }
        ],
        name: 'Approval',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'from', type: 'address' },
          { indexed: true, name: 'to', type: 'address' },
          { indexed: false, name: 'value', type: 'uint256' }
        ],
        name: 'Transfer',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'previousOwner', type: 'address' },
          { indexed: true, name: 'newOwner', type: 'address' }
        ],
        name: 'OwnershipTransferred',
        type: 'event'
      },
      {
        constant: true,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'userAddress', type: 'address' }
        ],
        name: 'isUserEnabledForContract',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: 'userAddress', type: 'address' }],
        name: 'isBalanceSufficientForContractCreation',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'qtyToLock', type: 'uint256' }
        ],
        name: 'lockTokensForTradingMarketContract',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'qtyToUnlock', type: 'uint256' }
        ],
        name: 'unlockTokens',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: true,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'userAddress', type: 'address' }
        ],
        name: 'getLockedBalanceForUser',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'qtyToLock', type: 'uint256' }],
        name: 'setLockQtyToAllowTrading',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'minBalance', type: 'uint256' }],
        name: 'setMinBalanceForContractCreation',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(web3: any, address: string | BigNumber): Promise<MarketToken> {
    const contract = new MarketToken(web3, address);
    const code = await promisify(web3.eth.getCode, [address]);

    // in case of missing smartcontract, code can be equal to "0x0" or "0x" depending on exact web3 implementation
    // to cover all these cases we just check against the source code length — there won't be any meaningful EVM program in less then 3 chars
    if (code.length < 4) {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get name(): Promise<string> {
    return promisify(this.rawWeb3Contract.name, []);
  }
  public get totalSupply(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.totalSupply, []);
  }
  public get INITIAL_SUPPLY(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.INITIAL_SUPPLY, []);
  }
  public get decimals(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.decimals, []);
  }
  public get upgradeableTarget(): Promise<string> {
    return promisify(this.rawWeb3Contract.upgradeableTarget, []);
  }
  public get minBalanceToAllowContractCreation(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.minBalanceToAllowContractCreation, []);
  }
  public get lockQtyToAllowTrading(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.lockQtyToAllowTrading, []);
  }
  public get owner(): Promise<string> {
    return promisify(this.rawWeb3Contract.owner, []);
  }
  public get symbol(): Promise<string> {
    return promisify(this.rawWeb3Contract.symbol, []);
  }
  public get totalUpgraded(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.totalUpgraded, []);
  }
  public balanceOf(_owner: BigNumber | string): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.balanceOf, [_owner.toString()]);
  }
  public allowance(_owner: BigNumber | string, _spender: BigNumber | string): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.allowance, [_owner.toString(), _spender.toString()]);
  }
  public isUserEnabledForContract(
    marketContractAddress: BigNumber | string,
    userAddress: BigNumber | string
  ): Promise<boolean> {
    return promisify(this.rawWeb3Contract.isUserEnabledForContract, [
      marketContractAddress.toString(),
      userAddress.toString()
    ]);
  }
  public isBalanceSufficientForContractCreation(userAddress: BigNumber | string): Promise<boolean> {
    return promisify(this.rawWeb3Contract.isBalanceSufficientForContractCreation, [
      userAddress.toString()
    ]);
  }
  public getLockedBalanceForUser(
    marketContractAddress: BigNumber | string,
    userAddress: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.getLockedBalanceForUser, [
      marketContractAddress.toString(),
      userAddress.toString()
    ]);
  }

  public approveTx(
    _spender: BigNumber | string,
    _value: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'approve', [
      _spender.toString(),
      _value.toString()
    ]);
  }
  public transferFromTx(
    _from: BigNumber | string,
    _to: BigNumber | string,
    _value: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'transferFrom', [
      _from.toString(),
      _to.toString(),
      _value.toString()
    ]);
  }
  public burnTx(_value: BigNumber | number): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'burn', [_value.toString()]);
  }
  public upgradeTx(value: BigNumber | number): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'upgrade', [value.toString()]);
  }
  public decreaseApprovalTx(
    _spender: BigNumber | string,
    _subtractedValue: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'decreaseApproval', [
      _spender.toString(),
      _subtractedValue.toString()
    ]);
  }
  public setUpgradeableTargetTx(
    upgradeAddress: BigNumber | string
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'setUpgradeableTarget', [
      upgradeAddress.toString()
    ]);
  }
  public transferTx(
    _to: BigNumber | string,
    _value: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'transfer', [
      _to.toString(),
      _value.toString()
    ]);
  }
  public increaseApprovalTx(
    _spender: BigNumber | string,
    _addedValue: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'increaseApproval', [
      _spender.toString(),
      _addedValue.toString()
    ]);
  }
  public transferOwnershipTx(newOwner: BigNumber | string): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'transferOwnership', [
      newOwner.toString()
    ]);
  }
  public lockTokensForTradingMarketContractTx(
    marketContractAddress: BigNumber | string,
    qtyToLock: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'lockTokensForTradingMarketContract', [
      marketContractAddress.toString(),
      qtyToLock.toString()
    ]);
  }
  public unlockTokensTx(
    marketContractAddress: BigNumber | string,
    qtyToUnlock: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'unlockTokens', [
      marketContractAddress.toString(),
      qtyToUnlock.toString()
    ]);
  }
  public setLockQtyToAllowTradingTx(
    qtyToLock: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'setLockQtyToAllowTrading', [
      qtyToLock.toString()
    ]);
  }
  public setMinBalanceForContractCreationTx(
    minBalance: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'setMinBalanceForContractCreation', [
      minBalance.toString()
    ]);
  }

  public UpdatedUserLockedBalanceEvent(eventFilter: {
    contractAddress?: BigNumber | string | Array<BigNumber | string>;
    userAddress?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    {
      contractAddress: BigNumber | string;
      userAddress: BigNumber | string;
      balance: BigNumber | number;
    },
    {
      contractAddress?: BigNumber | string | Array<BigNumber | string>;
      userAddress?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      {
        contractAddress: BigNumber | string;
        userAddress: BigNumber | string;
        balance: BigNumber | number;
      },
      {
        contractAddress?: BigNumber | string | Array<BigNumber | string>;
        userAddress?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'UpdatedUserLockedBalance', eventFilter);
  }
  public UpgradedEvent(eventFilter: {
    from?: BigNumber | string | Array<BigNumber | string>;
    to?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { from: BigNumber | string; to: BigNumber | string; value: BigNumber | number },
    {
      from?: BigNumber | string | Array<BigNumber | string>;
      to?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { from: BigNumber | string; to: BigNumber | string; value: BigNumber | number },
      {
        from?: BigNumber | string | Array<BigNumber | string>;
        to?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'Upgraded', eventFilter);
  }
  public BurnEvent(eventFilter: {
    burner?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { burner: BigNumber | string; value: BigNumber | number },
    { burner?: BigNumber | string | Array<BigNumber | string> }
  > {
    return new DeferredEventWrapper<
      { burner: BigNumber | string; value: BigNumber | number },
      { burner?: BigNumber | string | Array<BigNumber | string> }
    >(this, 'Burn', eventFilter);
  }
  public ApprovalEvent(eventFilter: {
    owner?: BigNumber | string | Array<BigNumber | string>;
    spender?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { owner: BigNumber | string; spender: BigNumber | string; value: BigNumber | number },
    {
      owner?: BigNumber | string | Array<BigNumber | string>;
      spender?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { owner: BigNumber | string; spender: BigNumber | string; value: BigNumber | number },
      {
        owner?: BigNumber | string | Array<BigNumber | string>;
        spender?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'Approval', eventFilter);
  }
  public TransferEvent(eventFilter: {
    from?: BigNumber | string | Array<BigNumber | string>;
    to?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { from: BigNumber | string; to: BigNumber | string; value: BigNumber | number },
    {
      from?: BigNumber | string | Array<BigNumber | string>;
      to?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { from: BigNumber | string; to: BigNumber | string; value: BigNumber | number },
      {
        from?: BigNumber | string | Array<BigNumber | string>;
        to?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'Transfer', eventFilter);
  }
  public OwnershipTransferredEvent(eventFilter: {
    previousOwner?: BigNumber | string | Array<BigNumber | string>;
    newOwner?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { previousOwner: BigNumber | string; newOwner: BigNumber | string },
    {
      previousOwner?: BigNumber | string | Array<BigNumber | string>;
      newOwner?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { previousOwner: BigNumber | string; newOwner: BigNumber | string },
      {
        previousOwner?: BigNumber | string | Array<BigNumber | string>;
        newOwner?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'OwnershipTransferred', eventFilter);
  }
}
