/* GENERATED BY TYPECHAIN VER. 0.2.4 */
/* tslint:disable */

import { BigNumber } from 'bignumber.js';
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper,
  DeferredEventWrapper
} from './typechain-runtime';

export class MarketCollateralPool extends TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: true,
        inputs: [],
        name: 'marketTradingHub',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: '', type: 'address' }, { name: '', type: 'address' }],
        name: 'tokenAddressToAccountBalance',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: '', type: 'address' }, { name: '', type: 'address' }],
        name: 'tokenAddressToBalanceLockTime',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'owner',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [{ name: '', type: 'address' }],
        name: 'contractAddressToCollateralPoolBalance',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      { inputs: [], payable: false, stateMutability: 'nonpayable', type: 'constructor' },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'collateralTokenAddress', type: 'address' },
          { indexed: true, name: 'user', type: 'address' },
          { indexed: false, name: 'balance', type: 'uint256' }
        ],
        name: 'UpdatedUserBalance',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'previousOwner', type: 'address' },
          { indexed: true, name: 'newOwner', type: 'address' }
        ],
        name: 'OwnershipTransferred',
        type: 'event'
      },
      {
        constant: true,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'userAddress', type: 'address' }
        ],
        name: 'getUserNetPosition',
        outputs: [{ name: '', type: 'int256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'userAddress', type: 'address' }
        ],
        name: 'getUserPositionCount',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'userAddress', type: 'address' },
          { name: 'index', type: 'uint256' }
        ],
        name: 'getUserPosition',
        outputs: [{ name: '', type: 'uint256' }, { name: '', type: 'int256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [
          { name: 'collateralTokenAddress', type: 'address' },
          { name: 'userAddress', type: 'address' }
        ],
        name: 'getUserUnallocatedBalance',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: 'collateralTokenAddress', type: 'address' },
          { name: 'depositAmount', type: 'uint256' }
        ],
        name: 'depositTokensForTrading',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'marketContractAddress', type: 'address' }],
        name: 'settleAndClose',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: 'marketContractAddress', type: 'address' },
          { name: 'maker', type: 'address' },
          { name: 'taker', type: 'address' },
          { name: 'qty', type: 'int256' },
          { name: 'price', type: 'uint256' }
        ],
        name: 'updatePositions',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'marketTradingHubAddress', type: 'address' }],
        name: 'setMarketTradingHubAddress',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        constant: false,
        inputs: [
          { name: 'collateralTokenAddress', type: 'address' },
          { name: 'withdrawAmount', type: 'uint256' }
        ],
        name: 'withdrawTokens',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<MarketCollateralPool> {
    const contract = new MarketCollateralPool(web3, address);
    const code = await promisify(web3.eth.getCode, [address]);

    // in case of missing smartcontract, code can be equal to "0x0" or "0x" depending on exact web3 implementation
    // to cover all these cases we just check against the source code length — there won't be any meaningful EVM program in less then 3 chars
    if (code.length < 4) {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get marketTradingHub(): Promise<string> {
    return promisify(this.rawWeb3Contract.marketTradingHub, []);
  }
  public get owner(): Promise<string> {
    return promisify(this.rawWeb3Contract.owner, []);
  }
  public tokenAddressToAccountBalance(
    arg0: BigNumber | string,
    arg1: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.tokenAddressToAccountBalance, [
      arg0.toString(),
      arg1.toString()
    ]);
  }
  public tokenAddressToBalanceLockTime(
    arg0: BigNumber | string,
    arg1: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.tokenAddressToBalanceLockTime, [
      arg0.toString(),
      arg1.toString()
    ]);
  }
  public contractAddressToCollateralPoolBalance(arg0: BigNumber | string): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.contractAddressToCollateralPoolBalance, [
      arg0.toString()
    ]);
  }
  public getUserNetPosition(
    marketContractAddress: BigNumber | string,
    userAddress: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.getUserNetPosition, [
      marketContractAddress.toString(),
      userAddress.toString()
    ]);
  }
  public getUserPositionCount(
    marketContractAddress: BigNumber | string,
    userAddress: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.getUserPositionCount, [
      marketContractAddress.toString(),
      userAddress.toString()
    ]);
  }
  public getUserPosition(
    marketContractAddress: BigNumber | string,
    userAddress: BigNumber | string,
    index: BigNumber | number
  ): Promise<[BigNumber, BigNumber]> {
    return promisify(this.rawWeb3Contract.getUserPosition, [
      marketContractAddress.toString(),
      userAddress.toString(),
      index.toString()
    ]);
  }
  public getUserUnallocatedBalance(
    collateralTokenAddress: BigNumber | string,
    userAddress: BigNumber | string
  ): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.getUserUnallocatedBalance, [
      collateralTokenAddress.toString(),
      userAddress.toString()
    ]);
  }

  public transferOwnershipTx(newOwner: BigNumber | string): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'transferOwnership', [
      newOwner.toString()
    ]);
  }
  public depositTokensForTradingTx(
    collateralTokenAddress: BigNumber | string,
    depositAmount: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'depositTokensForTrading', [
      collateralTokenAddress.toString(),
      depositAmount.toString()
    ]);
  }
  public settleAndCloseTx(
    marketContractAddress: BigNumber | string
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'settleAndClose', [
      marketContractAddress.toString()
    ]);
  }
  public updatePositionsTx(
    marketContractAddress: BigNumber | string,
    maker: BigNumber | string,
    taker: BigNumber | string,
    qty: BigNumber | number,
    price: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'updatePositions', [
      marketContractAddress.toString(),
      maker.toString(),
      taker.toString(),
      qty.toString(),
      price.toString()
    ]);
  }
  public setMarketTradingHubAddressTx(
    marketTradingHubAddress: BigNumber | string
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'setMarketTradingHubAddress', [
      marketTradingHubAddress.toString()
    ]);
  }
  public withdrawTokensTx(
    collateralTokenAddress: BigNumber | string,
    withdrawAmount: BigNumber | number
  ): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'withdrawTokens', [
      collateralTokenAddress.toString(),
      withdrawAmount.toString()
    ]);
  }

  public UpdatedUserBalanceEvent(eventFilter: {
    collateralTokenAddress?: BigNumber | string | Array<BigNumber | string>;
    user?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    {
      collateralTokenAddress: BigNumber | string;
      user: BigNumber | string;
      balance: BigNumber | number;
    },
    {
      collateralTokenAddress?: BigNumber | string | Array<BigNumber | string>;
      user?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      {
        collateralTokenAddress: BigNumber | string;
        user: BigNumber | string;
        balance: BigNumber | number;
      },
      {
        collateralTokenAddress?: BigNumber | string | Array<BigNumber | string>;
        user?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'UpdatedUserBalance', eventFilter);
  }
  public OwnershipTransferredEvent(eventFilter: {
    previousOwner?: BigNumber | string | Array<BigNumber | string>;
    newOwner?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { previousOwner: BigNumber | string; newOwner: BigNumber | string },
    {
      previousOwner?: BigNumber | string | Array<BigNumber | string>;
      newOwner?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { previousOwner: BigNumber | string; newOwner: BigNumber | string },
      {
        previousOwner?: BigNumber | string | Array<BigNumber | string>;
        newOwner?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'OwnershipTransferred', eventFilter);
  }
}
