/* GENERATED BY TYPECHAIN VER. 0.2.4 */
/* tslint:disable */

import { BigNumber } from 'bignumber.js';
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper,
  DeferredEventWrapper
} from './typechain-runtime';

export class MarketContract extends TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: true,
        inputs: [],
        name: 'creator',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'lastPrice',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'PRICE_DECIMAL_PLACES',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'COLLATERAL_TOKEN_ADDRESS',
        outputs: [{ name: '', type: 'address' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'isSettled',
        outputs: [{ name: '', type: 'bool' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'CONTRACT_NAME',
        outputs: [{ name: '', type: 'string' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'PRICE_CAP',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'EXPIRATION',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'PRICE_FLOOR',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'QTY_MULTIPLIER',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: true,
        inputs: [],
        name: 'settlementPrice',
        outputs: [{ name: '', type: 'uint256' }],
        payable: false,
        stateMutability: 'view',
        type: 'function'
      },
      {
        constant: false,
        inputs: [{ name: 'newCreator', type: 'address' }],
        name: 'transferCreator',
        outputs: [],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'function'
      },
      {
        inputs: [
          { name: 'contractName', type: 'string' },
          { name: 'baseAddresses', type: 'address[2]' },
          { name: 'contractSpecs', type: 'uint256[5]' }
        ],
        payable: false,
        stateMutability: 'nonpayable',
        type: 'constructor'
      },
      {
        anonymous: false,
        inputs: [{ indexed: false, name: 'price', type: 'uint256' }],
        name: 'UpdatedLastPrice',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [{ indexed: false, name: 'settlePrice', type: 'uint256' }],
        name: 'ContractSettled',
        type: 'event'
      },
      {
        anonymous: false,
        inputs: [
          { indexed: true, name: 'currentCreator', type: 'address' },
          { indexed: true, name: 'newCreator', type: 'address' }
        ],
        name: 'CreatorTransferred',
        type: 'event'
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(web3: any, address: string | BigNumber): Promise<MarketContract> {
    const contract = new MarketContract(web3, address);
    const code = await promisify(web3.eth.getCode, [address]);

    // in case of missing smartcontract, code can be equal to "0x0" or "0x" depending on exact web3 implementation
    // to cover all these cases we just check against the source code length — there won't be any meaningful EVM program in less then 3 chars
    if (code.length < 4) {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get creator(): Promise<string> {
    return promisify(this.rawWeb3Contract.creator, []);
  }
  public get lastPrice(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.lastPrice, []);
  }
  public get PRICE_DECIMAL_PLACES(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.PRICE_DECIMAL_PLACES, []);
  }
  public get COLLATERAL_TOKEN_ADDRESS(): Promise<string> {
    return promisify(this.rawWeb3Contract.COLLATERAL_TOKEN_ADDRESS, []);
  }
  public get isSettled(): Promise<boolean> {
    return promisify(this.rawWeb3Contract.isSettled, []);
  }
  public get CONTRACT_NAME(): Promise<string> {
    return promisify(this.rawWeb3Contract.CONTRACT_NAME, []);
  }
  public get PRICE_CAP(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.PRICE_CAP, []);
  }
  public get EXPIRATION(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.EXPIRATION, []);
  }
  public get PRICE_FLOOR(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.PRICE_FLOOR, []);
  }
  public get QTY_MULTIPLIER(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.QTY_MULTIPLIER, []);
  }
  public get settlementPrice(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.settlementPrice, []);
  }

  public transferCreatorTx(newCreator: BigNumber | string): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, 'transferCreator', [
      newCreator.toString()
    ]);
  }

  public UpdatedLastPriceEvent(eventFilter: {}): DeferredEventWrapper<
    { price: BigNumber | number },
    {}
  > {
    return new DeferredEventWrapper<{ price: BigNumber | number }, {}>(
      this,
      'UpdatedLastPrice',
      eventFilter
    );
  }
  public ContractSettledEvent(eventFilter: {}): DeferredEventWrapper<
    { settlePrice: BigNumber | number },
    {}
  > {
    return new DeferredEventWrapper<{ settlePrice: BigNumber | number }, {}>(
      this,
      'ContractSettled',
      eventFilter
    );
  }
  public CreatorTransferredEvent(eventFilter: {
    currentCreator?: BigNumber | string | Array<BigNumber | string>;
    newCreator?: BigNumber | string | Array<BigNumber | string>;
  }): DeferredEventWrapper<
    { currentCreator: BigNumber | string; newCreator: BigNumber | string },
    {
      currentCreator?: BigNumber | string | Array<BigNumber | string>;
      newCreator?: BigNumber | string | Array<BigNumber | string>;
    }
  > {
    return new DeferredEventWrapper<
      { currentCreator: BigNumber | string; newCreator: BigNumber | string },
      {
        currentCreator?: BigNumber | string | Array<BigNumber | string>;
        newCreator?: BigNumber | string | Array<BigNumber | string>;
      }
    >(this, 'CreatorTransferred', eventFilter);
  }
}
